%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(doordoor_types).

-include("doordoor_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('User') ->
  {struct, [{1, i64},
          {2, string},
          {3, i32}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('User') ->
  {struct, [{1, undefined, i64, 'id', undefined},
          {2, undefined, string, 'username', undefined},
          {3, undefined, i32, 'state',   0}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

